init dev
rainset/gophkeeper pull request #1
Opened 2023-02-13 04:31 UTC by rainset

2023-02-16 19:25 UTC, kilchik requested changes

2023-02-16 19:25 UTC, kilchik commented on cmd/client/main.go
> +		err := os.MkdirAll(cfg.ClientFolder, os.ModePerm)
0o777 - явно неподходящее разрешение для директории с секретами - любой пользователь любой группы может их прочитать и перетереть

2023-02-16 19:25 UTC, kilchik commented on cmd/client/main.go
> +	a := app.New(ctx, cfg)
Не увидел использования ctx в main. Ctx должен передавать в Run, при получении сигнала из ctx.Done() Run должен корректно завершаться. Сейчас сигнал ОС просто будет проигнорирован, приложение завершится, не дождавшись завершения всех производимых работ

2023-02-16 19:25 UTC, kilchik commented on internal/server/handler/handler.go
> +		logger.Error(err)
Все логи должны содержать все необходимые поля с деталями (user_id и пр, но не чувствительные данные), а также должны быть снабжены префиксом, позволяющим однозначно локализовать ошибку по логам

2023-02-16 19:25 UTC, kilchik commented on internal/server/handler/handler.go
> +	err = h.service.SaveCard(rb)
Выходит все данные хранятся в базе без шифрования, и в случае слива БД злоумышленник сможет воспользоваться всеми сохраненными банковскими картами? Так быть не должно, в БД любая чувствительная информация должна хоть как-то обфусцирована/зашифрована

2023-02-16 19:25 UTC, kilchik commented on internal/server/storage/storage.go
> +		_, err = d.pgx.Exec(d.ctx, sql, card.UserID, card.Title, card.Number, card.Date, card.Cvv, card.Meta, time.Now())
Контекст во всех запросах к базе должен браться из контекста хэндлера. Нет никакого смысла передавать context.Background в такие запросы. Контекст в запросе к БД нужен для того, чтобы при обрыве соединения/таймауте подвисший запрос мог завершиться, а вместе с ним и горутина с хэндлером.
Представь, что БД сильно нагружена, не справляется с запросами. Вопреки тому, что клиенты будут отваливаться от сервера по таймауту, соединения с БД будут продолжать висеть, пока не исчерпается их лимит. В итоге несколько долгих запросов подвесят все приложение

2023-02-16 19:25 UTC, kilchik commented on internal/client/app/app.go
> +		err = a.AddCard(cardData)
Локально данные тоже не должны храниться в plain text

2023-02-16 19:25 UTC, kilchik commented on cmd/server/main.go
> +package main
А где тесты? По заданию 80% кода должно быть покрыто тестами

2023-02-16 19:25 UTC, kilchik commented on internal/client/service/http.go
> +func (s *HTTPService) DeleteCard(accessToken string, extID int) (err error) {
А где методы для сохранения карты и пр данных? Как данные передаются на сервер клиентом?

2023-02-16 19:25 UTC, kilchik commented on internal/client/service/http.go
> +	res, err := client.R().
Все данные должны передаваться по https - это же все-таки пароли/банк карты

2023-02-16 19:25 UTC, kilchik commented on README.md
> +# Менеджер паролей GophKeeper
Я бы ожидал в README описания того, что было выполнено из этих требований и немножко про выбранные технологии и подходы

2023-03-21 20:01 UTC, lostsequence commented on internal/server/handler/handler.go
> +		logger.Error(err)
этот комментарий не поправлен

2023-03-21 20:16 UTC, lostsequence commented on cmd/server/main.go
> +package main
попробуй пожалуйста добавить еще тесты для хендлеров

2023-03-21 20:19 UTC, lostsequence commented on internal/server/app/app.go
> +
пустая строка

2023-03-21 20:20 UTC, lostsequence commented on internal/server/app/app.go
> +	ctx := context.Background()
пустой контекст особого смысла передавать нет
можно сделать withCancel и cancel вызвать после <-quit
так же можешь рассмотреть конструкцию NotifyContext

2023-03-21 20:23 UTC, lostsequence commented on internal/server/app/app.go
> +		}
по хорошему надо бы подождать горутину, чтобы удаление завершилось штатно на завершение приложения. Можно реализовать с помощью wait group
можно селектом слушать контекст и на <-done прервать цикл и перевести вейт группу в done

2023-03-21 20:24 UTC, lostsequence commented on internal/server/app/app.go
> +	store := storage.New(ctx, cfg.DatabaseDsn)
на завершение приложения коннекшн к базе тоже нужно закрыть

2023-03-21 20:31 UTC, lostsequence commented on internal/client/service/http_test.go
> +	t.Skipped()
почему решил скипнуть ?

2023-03-21 20:35 UTC, lostsequence commented on internal/server/storage/storage.go
> +}
обычно таких больших интерфейсов стараются избегать
в целом интерфейсы хорошо объявлять в месте их использования (тогда сервисы тоже надо будет разбить  по их зонам ответственности), таким образом каждый сервис будет использовать интерфейс с заметно меньшим количеством методов.
Это можно не исправлять, как совет.

2023-03-22 11:17 UTC, rainset commented on internal/server/storage/storage.go
> +}
понял, изначально не планировал приложение с несколькими сущностями для данных, времени разделить уже нет)
а так можно было разнести интерфейсы по типу данных

2023-03-22 11:19 UTC, rainset commented on internal/client/service/http_test.go
> +	t.Skipped()
добавил тесты для хендлеров сервера, в них думаю тоже самое, не стал делать

2023-03-22 11:19 UTC, rainset commented on internal/server/app/app.go
> +	store := storage.New(ctx, cfg.DatabaseDsn)
добавил

2023-03-22 11:19 UTC, rainset commented on internal/server/app/app.go
> +		}
добавил waitGroup

2023-03-22 11:20 UTC, rainset commented on internal/server/app/app.go
> +	ctx := context.Background()
поменял контекст

2023-03-22 11:20 UTC, rainset commented on internal/server/app/app.go
> +
убрал

2023-03-22 11:20 UTC, rainset commented on cmd/server/main.go
> +package main
добавил

2023-03-22 11:20 UTC, rainset commented on internal/server/handler/handler.go
> +		logger.Error(err)
сделал более информативные логи

2023-03-23 18:52 UTC, lostsequence commented on internal/server/app/app.go
> +			time.Sleep(60 * time.Second)
вместо time.sleep лучше ticker

2023-03-23 18:54 UTC, lostsequence commented on internal/server/app/app.go
> +			err := newService.ClearExpiredRefreshTokens(ctx)
тут надо еще слушать отмену контекста иначе wg.Done() не отработает

2023-03-23 18:56 UTC, lostsequence commented on internal/client/app/app.go
> +		//log.Println("id", id)
закоменченный код

2023-03-23 19:06 UTC, lostsequence commented on internal/server/app/app.go
> +	return s.httpServer.ListenAndServeTLS("./cert/cert.pem", "./cert/private.key")
лучше пути к сертам дать возможность задавать пользователю

2023-03-23 20:18 UTC, lostsequence approved these changes

2023-03-24 03:07 UTC, merged